// Generated by CoffeeScript 1.6.2
var HtmlTempalate;

module.exports = HtmlTempalate = (function() {
  HtmlTempalate.prototype.brunchPlugin = true;

  HtmlTempalate.prototype.type = 'template';

  HtmlTempalate.prototype.extension = 'html';

  function HtmlTempalate(config) {
    if (config.ngTemplate !== void 0) {
      this.templateDir = config.ngTemplate.template;
      if (this.templateDir.slice(-1) !== "/") {
        this.templateDir = this.templateDir + "/";
      }
    } else {
      this.templateDir = void 0;
    }
  }

  HtmlTempalate.prototype.compile = function(data, path, callback) {
    var head, tail;

    if ((this.templateDir !== void 0) && (path.indexOf(this.templateDir) !== -1)) {
      path = path.slice(this.templateDir.length);
    }
    head = "<script type='text/ng-template' id='" + path + "'>\n";
    tail = "</script>\n";
    return callback(null, head + data + tail);
  };

  return HtmlTempalate;

})();
