// Generated by CoffeeScript 1.6.2
var HtmlTempalate;

module.exports = HtmlTempalate = (function() {
  HtmlTempalate.prototype.brunchPlugin = true;

  HtmlTempalate.prototype.type = 'template';

  HtmlTempalate.prototype.extension = 'html';

  function HtmlTempalate(config) {
    var _ref, _ref1, _ref2;

    this.templateDir = (_ref = config != null ? (_ref1 = config.plugins) != null ? (_ref2 = _ref1.ngTemplate) != null ? _ref2.template : void 0 : void 0 : void 0) != null ? _ref : "";
  }

  HtmlTempalate.prototype.compile = function(data, path, callback) {
    var err, error, result;

    try {
      path = path.replace(this.templateDir, '');
      result = "<script type='text/ng-template' id='" + path + "'>" + data + "</script>";
    } catch (_error) {
      err = _error;
      error = "Template minify failed on " + path + ": " + err;
    }
    return process.nextTick(function() {
      return callback(error, result);
    });
  };

  return HtmlTempalate;

})();
